/*
 * Copyright (c) 2008-2017 Maxifier Ltd. All Rights Reserved.
 */
package com.yolkin.bookservice;

import com.yolkin.bookservice.annotations.listeners.BookListener;
import com.yolkin.bookservice.annotations.listeners.CommonDebugListener;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author dmitry.yolkin (dmitry.yolkin@maxifier.com) (2017-04-17 07:22)
 */
@Entity
@EntityListeners({BookListener.class, CommonDebugListener.class})
@NamedQueries({
        //JPQL - Java Persistence Query Language
        @NamedQuery(name = "findAllBooks", query = "SELECT b from Book b"),
        @NamedQuery(name = "findBookH2G2", query =
                "SELECT b from Book b WHERE b.title = 'H2G2'"
        )
})
public class Book {
    //id is primary key auto-generated by DB
    @Id
    @GeneratedValue
    private Long id;

    @NotNull
    private String title;
    private Float price;

    @Size(min = 10, max = 2000)
    private String description;
    private String number;

    public Book() {
        //default constructor for EclipseLink
    }

    public Book(String title, Float price, String description, String number) {
        this.title = title;
        this.price = price;
        this.description = description;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Override
    public String toString() {
        return "Book{" +
                "title='" + title + '\'' +
                ", price=" + price +
                ", description='" + description + '\'' +
                ", number='" + number + '\'' +
                '}';
    }
}